# wrangler.toml
name = "gemini-proxy-panel2"
main = "worker/src/index.ts"
compatibility_date = "2025-03-27"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "public"

[observability]
enabled = true

[triggers]
crons = ["*/30 * * * *"]

[[kv_namespaces]]
binding = "GEMINI_KEYS_KV"
id = "d1dc1594fbbc4803aec163e5bdce9669"

[[kv_namespaces]]
binding = "WORKER_CONFIG_KV"
id = "f90ac8f523c740c7bf8d7b97646090e9"
